markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - index.md
  - style.md
  - text-renderer.md

site_name: Palign
site_url: https://palign.dev/

theme:
  name: material
